import os
print("test1")
print("test2")
print("test3")
print("test4")
print("test5")
print("test6")
print("test7")
print("test8")
print("test9")
print("test10")
print("test11")
print("test12")
print("test13")
print("test14")
print("plus")
print("minus")
print("multiply")